// filepath: .github/workflows/quarto-render.yml
name: Render Quarto book
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Quarto
        uses: quarto-dev/quarto-action@v2
        with:
          version: latest
      - uses: actions/setup-python@v4
        with: {python-version: "3.10"}
      - run: pip install jupytext nbformat pyyaml
      - run: quarto render memm_book --no-cache
      - run: ls -la memm_book/_site || true