#!/usr/bin/env python3
"""One-shot migration: MyST Markdown pages (``book/``) -> marimo-book (``content/``).

MyST and Material share most of their Markdown dialect; what needs changing:

* ``{cite}`key``` -> ``[@key]`` -- marimo-book resolves that form itself.
* ``{tableofcontents}`` / ``{bibliography}`` directives have no Material
  equivalent (the sidebar nav and the auto-generated References section cover
  them), so they are dropped.
* ``{admonition}`` blocks -> Material admonitions (``!!! note``).
* Page links: ``Foo.ipynb`` -> ``chapter-Foo.md``. The staged tree holds
  ``.md`` for both hand-written pages and rendered notebooks, and mkdocs
  validates links against the staged tree.
* Image paths: ``fig/x.png`` / ``../img/x.png`` -> ``../images/x.png``, which is
  the single level of ``../`` marimo-book rewrites to ``images/``.

Chapter intro pages also carry an autogenerated page list; it is regenerated
from the book.yml TOC so it matches the new flat filenames and ordering.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
LEGACY = ROOT / "legacy" / "book"
CONTENT = ROOT / "content"

ADMONITION_TYPES = {
    "note": "note", "tip": "tip", "warning": "warning", "danger": "danger",
    "caution": "warning", "important": "important", "attention": "important",
    "hint": "tip", "seealso": "seealso", "admonition": "note",
}

ADMONITION_KINDS = (
    "admonition|note|tip|warning|danger|caution|important|attention|hint|seealso"
)
ADMONITION_HEADING = re.compile(
    r"^(\s*)\{(?P<kind>" + ADMONITION_KINDS + r")\}\s*(?P<title>.*?)\s*$"
)
CITE_ROLE = re.compile(r"\{cite\}`([^`]+)`")
TOC_DIRECTIVE = re.compile(r"^\s*\{tableofcontents\}\s*$", re.M)
BIBLIOGRAPHY_DIRECTIVE = re.compile(r"^\s*\{bibliography\}[^\n]*$", re.M)
# A list item whose link target does not exist. The link may be followed by a
# description, and the whole item is dropped when the target is dead.
LIST_ITEM_LINK = re.compile(r"^\s*(?:[-*+]|\d+[.)])\s+\[([^\]]+)\]\(([^)\s]+)\)")

# Links that pointed at a page which never existed in the legacy book either.
# `introduction_linear_regression` was a Python 2, nbformat-3 script in
# `book/scripts/`, never a notebook, but the legacy `_toc.yaml` and two
# "ordered reading" lists referenced it as `.ipynb`. They have always 404'd;
# carrying them forward would fail `marimo-book build --strict`.
DEAD_LINK_STEMS = {"introduction_linear_regression"}


def drop_dead_links(text: str) -> str:
    """Remove list items whose only target is a page that does not exist."""
    out = []
    for line in text.splitlines(keepends=True):
        m = LIST_ITEM_LINK.match(line.rstrip("\n"))
        if m and m.group(2).rsplit("/", 1)[-1].rsplit(".", 1)[0] in DEAD_LINK_STEMS:
            continue
        out.append(line)
    return "".join(out)


def rewrite_links(text: str, flat_names: dict[str, str]) -> str:
    """Retarget ``.ipynb`` / ``.md`` links at the flattened content filenames."""
    def sub(match: re.Match) -> str:
        label, target = match.group(1), match.group(2)
        if target.startswith(("http://", "https://", "#", "mailto:")):
            return match.group(0)
        filename = target.rsplit("/", 1)[-1]
        stem = filename.rsplit(".", 1)[0]
        new_stem = flat_names.get(stem)
        if not new_stem:
            return match.group(0)
        # The directory component is dropped: `content/` is flat, so every page
        # is a sibling. Legacy links like `../calibration/t-test.ipynb` would
        # otherwise point one level too high.
        # The source text often doubles as the link label ("t-test.ipynb").
        # Point the label at the new name so readers do not see a stale
        # `.ipynb` filename on a page that is no longer one.
        if label.rsplit(".", 1)[0] == stem and label.endswith((".ipynb", ".md")):
            label = f"{new_stem}.md"
        return f"[{label}]({new_stem}.md)"

    return re.sub(r"\[([^\]]+)\]\(([^)\s]+\.(?:ipynb|md))\)", sub, text)


def rewrite_images(text: str) -> str:
    """Point every *image* at the book-root ``images/`` directory.

    Only image syntax is touched -- ``![alt](path)`` and HTML ``src="path"``.
    Ordinary page links must keep their path or ``rewrite_links`` cannot retarget
    them.
    """
    def sub(match: re.Match) -> str:
        prefix, target = match.group(1), match.group(2)
        if target.startswith(("http://", "https://")):
            return match.group(0)
        name = target.rsplit("/", 1)[-1]
        return f"{prefix}../images/{name}"

    text = re.sub(r"(?P<prefix>!\[[^\]]*\]\()(?P<target>[^)\s]+)", sub, text)
    return re.sub(r"(?P<prefix>\bsrc=\")(?P<target>[^\"]+)", sub, text)


# A malformed image tag from the Jupyter Book era, where HTML attributes were
# pasted inside a Markdown link:
#     ![](fig/rod_length.png" alt="image" height=300px/>
# Material expresses the same intent with the `attr_list` syntax.
BROKEN_IMAGE_TAG = re.compile(
    r'!\[\]\(\s*(?P<path>[^)"\s]+)\s*"\s*alt\s*=\s*"[^"]*"\s*height\s*=\s*(?P<h>\d+)\s*px\s*/?>'
)


def fix_broken_image_tags(text: str) -> str:
    return BROKEN_IMAGE_TAG.sub(
        lambda m: f"![](../images/{m.group('path').rsplit('/', 1)[-1]}){{ height={m.group('h')} }}",
        text,
    )


def convert_admonitions(text: str) -> str:
    """``{admonition} title`` -> a Material ``!!! <type> "title"`` block."""
    out = []
    lines = text.splitlines(keepends=True)
    i = 0
    while i < len(lines):
        line = lines[i]
        m = ADMONITION_HEADING.match(line.rstrip("\n"))
        if not m:
            out.append(line)
            i += 1
            continue
        indent, kind, title = m.group(1), m.group(2), m.group(3)
        mapped = ADMONITION_TYPES[kind]
        header = f'{indent}!!! {mapped}' + (f' "{title}"' if title else "")
        out.append(header + "\n")
        i += 1
        # Indent the body one level so it belongs to the admonition.
        while i < len(lines):
            nxt = lines[i]
            if not nxt.strip():
                out.append(nxt)
                i += 1
                continue
            if re.match(rf"^\s*\{{{ADMONITION_TYPES}\b|^\s*#{{1,6}}\s|^\s*\[\^", nxt):
                break
            out.append("    " + nxt if nxt.strip() else nxt)
            i += 1
    return "".join(out)


def regenerate_autogen(text: str, pages: list[tuple[str, str]]) -> str:
    """Rebuild the ``Pages in this chapter`` list for a chapter intro page."""
    start = text.find("<!-- AUTOGEN_START -->")
    end = text.find("<!-- AUTOGEN_END -->")
    if start == -1 or end == -1:
        return text
    lines = ["<!-- AUTOGEN_START -->", "## Pages in this chapter", ""]
    for title, target in pages:
        lines.append(f"- [{title}]({target})")
    lines += ["", "<!-- AUTOGEN_END -->"]
    return text[:start] + "\n".join(lines) + "\n" + text[end + len("<!-- AUTOGEN_END -->") :]


def strip_frontmatter(text: str) -> str:
    return re.sub(r"\A---\n.*?\n---\n", "", text, flags=re.S)


def title_of(path: Path, fallback: str) -> str:
    """Best-effort page title: first ``#`` heading of the page.

    Handles both Markdown sources and legacy ``.ipynb`` (whose text lives inside
    JSON string arrays, so it has to be parsed rather than grepped).
    """
    try:
        text = path.read_text()
    except OSError:
        return fallback
    if path.suffix == ".ipynb":
        try:
            nb = json.loads(text)
        except json.JSONDecodeError:
            return fallback
        chunks = [
            "".join(c.get("source", []))
            for c in nb.get("cells", [])
            if c.get("cell_type") == "markdown"
        ]
        text = "\n".join(chunks)
    m = re.search(r"^#\s+(.+?)\s*$", text, re.M)
    return m.group(1) if m else fallback


def convert_page(src: Path, flat_names: dict[str, str], autogen: list | None) -> tuple[str, str]:
    text = src.read_text()
    text = strip_frontmatter(text)
    text = CITE_ROLE.sub(lambda m: f"[@{m.group(1)}]", text)
    text = TOC_DIRECTIVE.sub("", text)
    text = BIBLIOGRAPHY_DIRECTIVE.sub("", text)
    text = convert_admonitions(text)
    text = fix_broken_image_tags(text)
    text = rewrite_images(text)
    text = rewrite_links(text, flat_names)
    text = drop_dead_links(text)
    if autogen is not None:
        text = regenerate_autogen(text, autogen)
    return text, title_of(src, src.stem)


def legacy_flat_name(rel: Path) -> str:
    """``book/theory/00_intro.md`` -> ``theory-intro``; ``book/intro.md`` -> ``intro``.

    Mirrors ``convert_legacy.flat_name`` and the generated ``book.yml``.
    """
    stem = rel.stem
    if rel.name in {"intro.md", "00_intro.md"} or stem == "intro":
        stem = "intro"
    return f"{rel.parent.name}-{stem}" if rel.parent != Path(".") else stem


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--toc",
        default=str(ROOT / "book.yml"),
        help="book.yml, used for the per-chapter page lists",
    )
    args = ap.parse_args()

    toc_doc = yaml.safe_load(Path(args.toc).read_text())

    def walk(entries, out):
        for e in entries:
            if "file" in e:
                out.append(e["file"])
            if e.get("children"):
                walk(e["children"], out)

    toc_files: list[str] = []
    walk(toc_doc["toc"], toc_files)
    toc_set = set(toc_files)

    # Legacy `book/...` path -> flat content filename, for every page the TOC names.
    flat_names: dict[str, str] = {}
    toc_by_chapter: dict[str, list[tuple[str, str]]] = {}
    legacy_for_flat: dict[str, Path] = {}
    for f in toc_files:
        p = Path(f)
        if not p.parts or p.parts[0] != "content":
            continue
        flat = p.stem
        chapter = flat.split("-", 1)[0] if "-" in flat else ""
        flat_names.setdefault(flat, flat)
        toc_by_chapter.setdefault(chapter, []).append((flat, p.suffix))
        # The legacy source for this page: a `.py` TOC entry came from a
        # `.ipynb`, so compare against the legacy extension, not the TOC one.
        legacy_suffix = ".ipynb" if p.suffix == ".py" else p.suffix
        for cand in sorted(LEGACY.rglob(f"*{legacy_suffix}")):
            if ".ipynb_checkpoints" in cand.parts:
                continue
            if legacy_flat_name(cand.relative_to(LEGACY)) == flat:
                legacy_for_flat[flat] = cand
                break
    # Legacy stems (without directory or extension) so old cross-links resolve.
    for src in LEGACY.rglob("*"):
        if src.suffix not in {".md", ".ipynb"} or ".ipynb_checkpoints" in src.parts:
            continue
        rel = src.relative_to(LEGACY)
        flat = legacy_flat_name(rel)
        # A notebook page is `page.ipynb` in the legacy tree but `page.py` in
        # book.yml, so accept either extension when testing TOC membership.
        if any(f"content/{flat}{ext}" in toc_set for ext in (".py", ".md", ".ipynb")):
            flat_names.setdefault(rel.stem, flat)

    md_sources = sorted(LEGACY.rglob("*.md"))
    print(f"converting {len(md_sources)} markdown pages")

    for src in md_sources:
        rel = src.relative_to(LEGACY)
        flat = legacy_flat_name(rel)
        chapter = rel.parent.name if rel.parent != Path(".") else ""
        in_toc = f"content/{flat}{rel.suffix}" in toc_set

        # Build this chapter's page list from the TOC, for the autogenerated block.
        autogen = None
        if flat.endswith("-intro"):
            autogen = []
            for sib, suffix in toc_by_chapter.get(chapter, []):
                if sib == flat or suffix != ".py":
                    continue
                src_page = legacy_for_flat.get(sib) or (CONTENT / f"{sib}.py")
                if not src_page.exists():
                    continue
                autogen.append((title_of(src_page, sib), f"{sib}.md"))
            if not autogen:
                autogen = None

        out_path = CONTENT / f"{flat}.md"
        text, _ = convert_page(src, flat_names, autogen)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text)
        print(f"  {rel} -> content/{out_path.name}{'' if in_toc else '  (not in TOC)'}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
